1) Qual foi a causa da exceção?
O Cliente tenta-se ligar ao servidor com parâmetros correctos, antes do servidor estar pronto a receber ligações.

2) Que exceção é que foi lançada?
Exception in thread "main" java.net.ConnectException: Connection refused

3) Em que linha do código do cliente é que foi lançada a exceção?
Linha 32: Socket socket = new Socket(host, port);

4) Ou será um problema na configuração dos argumentos?
Não, os argumentos estão todos correctos, mas como o servidor não está pronto a receber, a ligação é recusada.
